"""create skills table

Revision ID: ed6cf72690a4
Revises: 289f7c110c05
Create Date: 2026-09-22 04:19:21.916214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6cf72690a4'
down_revision: Union[str, Sequence[str], None] = '289f7c110c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skills_name_key'), 'skills', type_='unique')
    op.create_unique_constraint('uq_skill_name', 'skills', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skill_name', 'skills', type_='unique')
    op.create_unique_constraint(op.f('skills_name_key'), 'skills', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
